services:
  client:
      build:
        context: ./client
        dockerfile: Dockerfile.dev
      working_dir: /app
      ports:
        - "4200:4200"
      volumes:
        - ./client:/app
        - /app/node_modules
      command: >
        sh -c "
          echo 'Waiting for backend...' &&
          while ! nc -z server 8080; do
            sleep 1
          done &&
          echo 'Backend is up!' &&
          npm install &&
          npm start -- --poll=2000 --host 0.0.0.0
        "
      environment:
        - WATCHPACK_POLLING=true
        - CHOKIDAR_USEPOLLING=true
      depends_on:
        server:
          condition: service_healthy
      networks:
        - yacht-net

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: yacht-charter-server-dev
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - ~/.m2:/root/.m2
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/yacht_charter?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
    networks:
      - yacht-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    restart: unless-stopped

networks:
  yacht-net:
    driver: bridge