services:
  client:
    build: ./client
    ports:
      - "4200:80"
    depends_on:
      - server
    networks:
      - yacht-net

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: yacht-charter-server
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/yacht_charter?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
    networks:
      - yacht-net
    restart: unless-stopped

networks:
  yacht-net:
    driver: bridge